version: '3'

services:
  app:
    build: .
    environment:
      - PORT=8501 # Para el acceso a los servicios de streamlit
    volumes:
      - "./src:/app"
      - "./data:/app/data"
      - "./model:/app/model"
    ports:
      - "8501:8501"